"""initial schema

Revision ID: 6d0228f70a73
Revises: 
Create Date: 2026-06-15 14:49:43.871738
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d0228f70a73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('suite', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('run_group', sa.String(length=255), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_parent_id'), 'runs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_runs_run_group'), 'runs', ['run_group'], unique=False)
    op.create_index(op.f('ix_runs_suite'), 'runs', ['suite'], unique=False)
    op.create_index(op.f('ix_runs_trace_id'), 'runs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_runs_version'), 'runs', ['version'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('suite', sa.String(length=255), nullable=False),
    sa.Column('test_case_id', sa.String(length=255), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('eval_type', sa.String(length=64), nullable=False),
    sa.Column('eval_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_suite'), 'test_cases', ['suite'], unique=False)
    op.create_index(op.f('ix_test_cases_test_case_id'), 'test_cases', ['test_case_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=255), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evaluator', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_run_id'), 'eval_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_eval_results_test_case_id'), 'eval_results', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_results_test_case_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_test_cases_test_case_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_suite'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_runs_version'), table_name='runs')
    op.drop_index(op.f('ix_runs_trace_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_suite'), table_name='runs')
    op.drop_index(op.f('ix_runs_run_group'), table_name='runs')
    op.drop_index(op.f('ix_runs_parent_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
